name: Gitea Docker Redeploy
run-name: ${{ gitea.actor }} is deploying new version
on: [push]
jobs:
  ssh_to_self_and_redeploy:
    name: Redploy-App-on-self-via-SSH
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            ls
            cd Ollama-Bot
            cd deployment
            docker-compose down
            git pull
            docker-compose build
            docker-compose push
            docker-compose up -d
    

