name: Gitea Docker Redeploy
run-name: ${{ gitea.actor }} is deploying new version
on: [push]

jobs:
  Explore-Gitea-Actions:
    #runs-on: ubuntu-latest
    steps:
      #- run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      #- run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"

      - name: List files in the repository
        run: |
          ls ~

      #- run: echo "🍏 This job's status is ${{ job.status }}."


